name: Node

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ğŸ›¬'
        
        uses: action/checkout@v4
      
      - name: 'Setup Node âš™ï¸'

        uses: actions/setup-node@v4
        
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: 'Install dependencies ğŸ“¦'
        run: npm ci

      - name: 'Build ğŸš€'
        run: npm run build && find dist/main.js

      - name: 'Run lint ğŸ’…ğŸ»'
        run: npm run lint

      - name: 'Run tests ğŸ§ª'
        run: npm run test


        